remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: Cibus Docs
description: Testing manuals and user guides for the Cibus Restaurant Platform

baseurl: "/cibus-issues"
url: "https://abbasali-io.github.io"

color_scheme: blackwhite

search_enabled: true

footer_content: "&copy; 2026 Cibus"

aux_links:
  "GitHub":
    - "https://github.com/abbasali-io/cibus-issues"

back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true
